[build]
  command = "npm run build:web"
  publish = "dist"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/repository/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
